name: 'Build proto plugin'
author: 'Miles Johnson'
description: 'Build, optimize, and prepare proto WASM plugins for release.'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'layers'
  color: 'red'
